version: "3"

services:
  nginx:
    build: .
    depends_on:
      - kutt
    ports:
      - "80:80"
    environment:
      - HSTS=off
      - HTTPS_METHOD=noredirect
    restart: always

  kutt:
    image: kutt/kutt
    depends_on:
      - postgres
      - redis
    # ports:
      # - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
